import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Quantifying Fairness in CPU Scheduling\n",
    "This interactive notebook demonstrates the execution of **First-Come, First-Served (FCFS)**, **Priority Scheduling**, and **Round Robin (RR)** using genuine supercomputer workloads from the Parallel Workloads Archive.\n",
    "\n",
    "The analysis measures the *Average Waiting Time*, *Response Time*, *Jain's Fairness Index*, and *Starvation Count* across three real-world traces (`SDSC-SP2`, `SDSC-BLUE`, and `ANL-Intrepid`) along with two synthetic distributions to simulate heavy-tail characteristics."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import os\n",
    "\n",
    "sns.set_style(\"whitegrid\")\n",
    "plt.rcParams['figure.figsize'] = (12, 6)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1. Data Loader & Generator\n",
    "Here we parse the raw `.swf` format traces and generate some extreme heavy-tail synthetic models."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_swf(filename, max_rows=200):\n",
    "    data = []\n",
    "    if not os.path.exists(filename):\n",
    "        print(f\"Warning: {filename} not found.\")\n",
    "        return pd.DataFrame()\n",
    "        \n",
    "    with open(filename, 'r') as f:\n",
    "        count = 0\n",
    "        for line in f:\n",
    "            line = line.strip()\n",
    "            if not line or line.startswith(';'): continue\n",
    "            parts = line.split()\n",
    "            if len(parts) < 18: continue\n",
    "            try:\n",
    "                pid = int(parts[0])\n",
    "                submit = float(parts[1])\n",
    "                run = float(parts[3])\n",
    "                req_procs = int(parts[7])\n",
    "                if run <= 0: run = 1 # give it at least 1ms to avoid DIV/0\n",
    "                prio = min(10, max(1, req_procs)) # proxy priority based on requested processors\n",
    "                data.append({'pid': pid, 'arrivalTime': submit, 'priority': prio, 'processTime': int(run)})\n",
    "                count += 1\n",
    "                if count >= max_rows: break\n",
    "            except ValueError:\n",
    "                continue\n",
    "    df = pd.DataFrame(data)\n",
    "    if not df.empty:\n",
    "        df.sort_values(by='arrivalTime', inplace=True)\n",
    "        df['arrivalTime'] = df['arrivalTime'] - df['arrivalTime'].min()\n",
    "    return df\n",
    "\n",
    "def generate_datasets():\n",
    "    datasets = {}\n",
    "    n_processes = 200\n",
    "\n",
    "    # 1. Real World: SDSC SP2 Trace\n",
    "    datasets['Real SDSC SP2'] = load_swf('SDSC-SP2.swf', n_processes)\n",
    "    # 2. Real World: SDSC BLUE Trace\n",
    "    datasets['Real SDSC BLUE'] = load_swf('SDSC-BLUE.swf', n_processes)\n",
    "    # 3. Real World: ANL Intrepid Trace\n",
    "    datasets['Real ANL Intrepid'] = load_swf('ANL-Intrepid.swf', n_processes)\n",
    "\n",
    "    # 4. Synthetic - Controlled Variance (Uniform distribution)\n",
    "    df_uniform = pd.DataFrame({\n",
    "        'pid': range(1, n_processes + 1),\n",
    "        'arrivalTime': np.sort(np.random.randint(0, 500, n_processes)),\n",
    "        'priority': np.random.randint(1, 11, n_processes),\n",
    "        'processTime': np.random.randint(10, 100, n_processes)\n",
    "    })\n",
    "    datasets['Synthetic Normal (Uniform)'] = df_uniform\n",
    "\n",
    "    # 5. Synthetic - High Heterogeneity (Pareto distribution)\n",
    "    df_pareto = pd.DataFrame({\n",
    "        'pid': range(1, n_processes + 1),\n",
    "        'arrivalTime': np.sort(np.random.randint(0, 1000, n_processes)),\n",
    "        'priority': np.random.randint(1, 11, n_processes),\n",
    "        'processTime': np.maximum(1, np.random.pareto(a=1.5, size=n_processes) * 40).astype(int)\n",
    "    })\n",
    "    datasets['Synthetic Heavy-Tail (Pareto)'] = df_pareto\n",
    "\n",
    "    return {k: v for k, v in datasets.items() if not v.empty}\n",
    "\n",
    "datasets = generate_datasets()\n",
    "print(\"Datasets generated/loaded:\", list(datasets.keys()))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. Fairness Metrics Calculator\n",
    "This function computes Wait Times, Throughput, Utilization, Jain's Fairness Index, and Gini Coefficients."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def calculate_extended_metrics(df, total_time, quantum=None):\n",
    "    df[\"TurnaroundTime\"] = df[\"FinishTime\"] - df[\"arrivalTime\"]\n",
    "    df[\"WaitingTime\"] = df[\"TurnaroundTime\"] - df[\"processTime\"]\n",
    "    df[\"ResponseTime\"] = df[\"StartTime\"] - df[\"arrivalTime\"]\n",
    "    \n",
    "    metrics = {}\n",
    "    metrics['AWT'] = df[\"WaitingTime\"].mean()\n",
    "    metrics['ATAT'] = df[\"TurnaroundTime\"].mean()\n",
    "    metrics['Response Time'] = df[\"ResponseTime\"].mean()\n",
    "    metrics['MWT'] = df[\"WaitingTime\"].max()\n",
    "    metrics['Throughput'] = len(df) / total_time if total_time > 0 else 0\n",
    "    \n",
    "    total_burst = df[\"processTime\"].sum()\n",
    "    metrics['CPU Utilization (%)'] = (total_burst / total_time) * 100 if total_time > 0 else 0\n",
    "    \n",
    "    sum_wt = df[\"WaitingTime\"].sum()\n",
    "    sum_sq_wt = (df[\"WaitingTime\"]**2).sum()\n",
    "    n = len(df)\n",
    "    metrics['JFI'] = (sum_wt**2) / (n * sum_sq_wt) if sum_sq_wt > 0 else 1.0\n",
    "    \n",
    "    def gini(array):\n",
    "        array = np.sort(array)\n",
    "        index = np.arange(1, array.shape[0] + 1)\n",
    "        nn = array.shape[0]\n",
    "        return (np.sum((2 * index - nn  - 1) * array)) / (nn * np.sum(array)) if np.sum(array) > 0 else 0\n",
    "    metrics['Gini (WT)'] = gini(df[\"WaitingTime\"].values)\n",
    "    \n",
    "    avg_burst = df[\"processTime\"].mean()\n",
    "    starvation_threshold = 3 * avg_burst\n",
    "    metrics['Starvation Count'] = len(df[df[\"WaitingTime\"] > starvation_threshold])\n",
    "    \n",
    "    metrics['Context-Switches'] = len(df)\n",
    "    if 'Preemptions' in df.columns:\n",
    "        metrics['Context-Switches'] += df['Preemptions'].sum()\n",
    "        \n",
    "    return metrics"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Schedulers (FCFS, Priority, Round Robin)\n",
    "Simulating the specific dispatch logic algorithm by algorithm."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def fcfs_schedule(df_in):\n",
    "    df = df_in.copy().sort_values(by='arrivalTime').reset_index(drop=True)\n",
    "    current_time = 0\n",
    "    start_times, finish_times = [], []\n",
    "    for arr, burst in zip(df['arrivalTime'], df['processTime']):\n",
    "        start = max(current_time, arr)\n",
    "        start_times.append(start)\n",
    "        finish = start + burst\n",
    "        finish_times.append(finish)\n",
    "        current_time = finish\n",
    "    df['StartTime'] = start_times\n",
    "    df['FinishTime'] = finish_times\n",
    "    df['Preemptions'] = 0\n",
    "    return df, current_time\n",
    "\n",
    "def priority_schedule(df_in): \n",
    "    # Non-preemptive, higher number = higher priority\n",
    "    df = df_in.copy().sort_values(by=['arrivalTime', 'priority'], ascending=[True, False]).reset_index(drop=True)\n",
    "    ready_queue = []\n",
    "    current_time = 0\n",
    "    completed = 0\n",
    "    n = len(df)\n",
    "    \n",
    "    start_times = np.zeros(n)\n",
    "    finish_times = np.zeros(n)\n",
    "    is_completed = np.zeros(n, dtype=bool)\n",
    "    \n",
    "    while completed < n:\n",
    "        arrived = df[(df['arrivalTime'] <= current_time) & (~is_completed)]\n",
    "        if arrived.empty:\n",
    "            next_arrival = df.loc[~is_completed, 'arrivalTime'].min()\n",
    "            current_time = next_arrival\n",
    "            arrived = df[(df['arrivalTime'] <= current_time) & (~is_completed)]\n",
    "            \n",
    "        # Pick highest priority\n",
    "        idx = arrived['priority'].idxmax()\n",
    "        start = current_time\n",
    "        burst = df.loc[idx, 'processTime']\n",
    "        finish = start + burst\n",
    "        \n",
    "        start_times[idx] = start\n",
    "        finish_times[idx] = finish\n",
    "        is_completed[idx] = True\n",
    "        \n",
    "        current_time = finish\n",
    "        completed += 1\n",
    "        \n",
    "    df['StartTime'] = start_times\n",
    "    df['FinishTime'] = finish_times\n",
    "    df['Preemptions'] = 0\n",
    "    return df, current_time\n",
    "\n",
    "def round_robin_schedule(df_in, quantum):\n",
    "    df = df_in.copy().sort_values(by='arrivalTime').reset_index(drop=True)\n",
    "    n = len(df)\n",
    "    remaining_burst = df['processTime'].values.copy()\n",
    "    start_times = np.full(n, -1.0)\n",
    "    finish_times = np.zeros(n)\n",
    "    preemptions = np.zeros(n)\n",
    "    \n",
    "    current_time = 0\n",
    "    completed = 0\n",
    "    queue = []\n",
    "    \n",
    "    idx_arrived = 0\n",
    "    \n",
    "    while completed < n:\n",
    "        while idx_arrived < n and df.loc[idx_arrived, 'arrivalTime'] <= current_time:\n",
    "            queue.append(idx_arrived)\n",
    "            idx_arrived += 1\n",
    "            \n",
    "        if not queue:\n",
    "            current_time = df.loc[idx_arrived, 'arrivalTime']\n",
    "            continue\n",
    "            \n",
    "        curr_proc = queue.pop(0)\n",
    "        if start_times[curr_proc] == -1:\n",
    "            start_times[curr_proc] = current_time\n",
    "            \n",
    "        time_to_run = min(quantum, remaining_burst[curr_proc])\n",
    "        current_time += time_to_run\n",
    "        remaining_burst[curr_proc] -= time_to_run\n",
    "        \n",
    "        while idx_arrived < n and df.loc[idx_arrived, 'arrivalTime'] <= current_time:\n",
    "            queue.append(idx_arrived)\n",
    "            idx_arrived += 1\n",
    "            \n",
    "        if remaining_burst[curr_proc] == 0:\n",
    "            finish_times[curr_proc] = current_time\n",
    "            completed += 1\n",
    "        else:\n",
    "            queue.append(curr_proc)\n",
    "            preemptions[curr_proc] += 1\n",
    "            \n",
    "    df['StartTime'] = start_times\n",
    "    df['FinishTime'] = finish_times\n",
    "    df['Preemptions'] = preemptions\n",
    "    return df, current_time"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 4. Running the Analysis and Presenting Results\n",
    "Executing the simulations across all datasets and charting out the results contextually inline."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "all_results = []\n",
    "\n",
    "for ds_name, ds_df in datasets.items():\n",
    "    mean_burst = ds_df['processTime'].mean()\n",
    "    quantum = int(mean_burst / 2) if int(mean_burst / 2) > 0 else 1\n",
    "    \n",
    "    # FCFS\n",
    "    res_fcfs, tt_fcfs = fcfs_schedule(ds_df)\n",
    "    m_fcfs = calculate_extended_metrics(res_fcfs, tt_fcfs)\n",
    "    m_fcfs['Algorithm'] = 'FCFS'\n",
    "    m_fcfs['Dataset'] = ds_name\n",
    "    \n",
    "    # Priority\n",
    "    res_prio, tt_prio = priority_schedule(ds_df)\n",
    "    m_prio = calculate_extended_metrics(res_prio, tt_prio)\n",
    "    m_prio['Algorithm'] = 'Priority'\n",
    "    m_prio['Dataset'] = ds_name\n",
    "    \n",
    "    # Round Robin\n",
    "    res_rr, tt_rr = round_robin_schedule(ds_df, quantum)\n",
    "    m_rr = calculate_extended_metrics(res_rr, tt_rr, quantum)\n",
    "    m_rr['Algorithm'] = 'Round Robin'\n",
    "    m_rr['Dataset'] = ds_name\n",
    "    \n",
    "    all_results.extend([m_fcfs, m_prio, m_rr])\n",
    "\n",
    "results_df = pd.DataFrame(all_results)\n",
    "\n",
    "# Display Dataframe of Metrics\n",
    "display(results_df.head())\n",
    "\n",
    "# Output visually inline\n",
    "metrics_to_plot = ['AWT', 'Response Time', 'JFI', 'Starvation Count']\n",
    "for metric in metrics_to_plot:\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    sns.barplot(data=results_df, x='Dataset', y=metric, hue='Algorithm')\n",
    "    plt.title(f'{metric} Comparison across Datasets')\n",
    "    plt.xticks(rotation=45, ha='right')\n",
    "    plt.tight_layout()\n",
    "    plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('c:/Users/adib/Desktop/OS_paper/Final_Scheduling_Analysis.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print("Notebook generated successfully!")
